# Generated by Django 6.0.7 on 2026-08-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_shop'),
        ('orders', '0003_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('event', 'number')},
        ),
    ]
