# Generated by Django 6.0.7 on 2026-07-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('country', models.CharField(choices=[('TH', 'Thailand'), ('SG', 'Singapore')], default='TH', max_length=2)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('booth_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('travel_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('hotel_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('food_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
